export default [
  {
    backgroundColor: "#040926",
    color: "#A3AFF5",
    category: "Healthcare",
    subCategories: ["Skincare", "Personal care", "Health", "Eye care"],
  },
  {
    backgroundColor: "#84732B",
    color: "#034C3C",
    category: "Food & Drinks",
    subCategories: [
      "Fruits & Vegetables",
      "Frozen Food",
      "Bakery",
      "Snacks & Desserts",
      "Alcoholic Beverages",
      "Noodles & Pasta",
      "Rice & Cooking oil",
    ],
  },
  {
    backgroundColor: "#F58A07",
    color: "#19381F",
    category: "Beauty",
    subCategories: ["Skincare", "Makeup", "Nail Care", "Perfume"],
  },
  {
    backgroundColor: "#944654",
    color: "#FDF0D5",
    category: "Babies & Kids",
    subCategories: [
      "Toys",
      "Trolleys",
      "LEGO®",
      "Electronics",
      "Puzzles",
      "Costumes",
      "Food",
      "Hygiene & Care",
      "Child's Room",
      "Feeding Accessories",
    ],
  },
  {
    backgroundColor: "#FC814A",
    color: "#DBDBDB",
    category: "Homeware",
    subCategories: [
      "Air Purifiers",
      "Stoves, Hoods & Ovens",
      "Refrigerators",
      "Coffee & Tea",
      "Air Conditioning",
      "Grilling",
      "Vacuum cleaners",
    ],
  },
];
